"""empty message

Revision ID: 018acf950548
Revises: 0c52faa0143d
Create Date: 2022-04-10 10:32:07.350694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018acf950548'
down_revision = '0c52faa0143d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('student', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
