"""empty message

Revision ID: 0c52faa0143d
Revises: 4b521146f09b
Create Date: 2022-04-10 10:20:02.029217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c52faa0143d'
down_revision = '4b521146f09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'student_id')
    op.drop_table('students')
    # ### end Alembic commands ###
