"""empty message

Revision ID: e008d19b7fff
Revises: bdc4c074adae
Create Date: 2022-04-09 18:41:25.201974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e008d19b7fff'
down_revision = 'bdc4c074adae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('lessonDate', sa.String(length=140), nullable=True))
    op.drop_column('lessons', 'date_of_lesson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('date_of_lesson', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'lessonDate')
    # ### end Alembic commands ###
